name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apjsa-fe/**'  # Thư mục frontend mới của bạn

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apjsa-fe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Test frontend
        run: npm test
